### ISSUE TITLE
domain must be nurse, 1 domain for 1 controller, hospital is the whole application

### ISSUE THREAD

**Issue by Japoivvb** [AlessandraRivasplata/Backend-con-Springboot#29]
https://github.com/AlessandraRivasplata/Backend-con-Springboot/blob/c16eac66753af4484cd2eb7400022c014cc079cc/src/main/java/com/hospital/controller/NurseController.java#L23

in case PatientController or DoctorController you cannot use same prefix url

**Comment by reivaX1755** [comment]
fixed in the #9 merge
